version: "3"
services:
  mongo:
    container_name: mongo_smart
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: app
    restart: on-failure
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo