version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: app
    restart: on-failure
    build: .
    volumes:
     - .:/app
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo